apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-controller-cm
data:
  NAMESPACE: {{ .Release.Namespace }}
  NUM_WORKERS: {{ .Values.numWorkers | quote }}
  VM_SYNC_DURATION_SECONDS: {{ .Values.vmResyncPeriodSeconds | quote }}
  HA_ENABLED: {{ .Values.ha.enabled | quote }}
  {{ if gt .Values.replicas 1.0 }}
  HA_ENABLED: "true"
  HA_LEASE_LOCK_NAME: {{ .Release.Name }}
  HA_LEASE_DURATION_SECONDS: {{ .Values.ha.leaderElection.leaseDurationSeconds | quote }}
  HA_RENEW_DEADLINE_SECONDS: {{ .Values.ha.leaderElection.renewDeadlineSeconds | quote }}
  HA_RETRY_PERIOD_SECONDS: {{ .Values.ha.leaderElection.retryPeriodSeconds | quote }}
  {{ end }}
  METRICS_ENABLED: {{ .Values.monitoring.enabled | quote }}
  {{ if .Values.monitoring.enabled }}
  METRICS_PATH: {{ .Values.monitoring.path }}
  METRICS_PORT: {{ .Values.monitoring.port | quote }}
  {{ end }}
  CLOUD_API_URL: {{ .Values.cloudApiUrl }}
