apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: sample-controller
  name: sample-controller-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 8000
    targetPort: metrics
  selector:
    control-plane: sample-controller
